"""Fix schema drift: add webhooks table, FK constraints, type fixes

Revision ID: cf90691b667e
Revises: e564635c20b3
Create Date: 2026-03-07 22:46:59.578268

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf90691b667e"
down_revision: Union[str, Sequence[str], None] = "e564635c20b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _fk_exists(
    conn: sa.engine.Connection,
    *,
    table: str,
    local_cols: tuple[str, ...],
    remote_table: str,
    remote_cols: tuple[str, ...],
) -> bool:
    if conn.dialect.name == "sqlite":
        rows = (
            conn.exec_driver_sql(f"PRAGMA foreign_key_list('{table}')").mappings().all()
        )
        fk_groups: dict[int, list[dict[str, object]]] = {}
        for row in rows:
            fk_groups.setdefault(int(row["id"]), []).append(row)

        for group in fk_groups.values():
            ordered = sorted(group, key=lambda item: int(item["seq"]))
            group_remote_table = str(ordered[0]["table"])
            group_local_cols = tuple(str(item["from"]) for item in ordered)
            group_remote_cols = tuple(str(item["to"]) for item in ordered)
            if (
                group_remote_table == remote_table
                and group_local_cols == local_cols
                and group_remote_cols == remote_cols
            ):
                return True
        return False

    inspector = sa.inspect(conn)
    for fk in inspector.get_foreign_keys(table):
        constrained = tuple(str(col) for col in (fk.get("constrained_columns") or ()))
        referred_table = str(fk.get("referred_table") or "")
        referred = tuple(str(col) for col in (fk.get("referred_columns") or ()))
        if (
            constrained == local_cols
            and referred_table == remote_table
            and referred == remote_cols
        ):
            return True
    return False


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    has_gateway_tenant_fk = _fk_exists(
        conn,
        table="gateway_requests",
        local_cols=("tenant_id",),
        remote_table="tenants",
        remote_cols=("tenant_id",),
    )
    has_metering_tenant_fk = _fk_exists(
        conn,
        table="metering_events",
        local_cols=("tenant_id",),
        remote_table="tenants",
        remote_cols=("tenant_id",),
    )
    has_organizations_tenant_fk = _fk_exists(
        conn,
        table="organizations",
        local_cols=("tenant_id",),
        remote_table="tenants",
        remote_cols=("tenant_id",),
    )
    has_tasks_org_fk = _fk_exists(
        conn,
        table="tasks",
        local_cols=("org_id",),
        remote_table="organizations",
        remote_cols=("org_id",),
    )
    has_tasks_tenant_fk = _fk_exists(
        conn,
        table="tasks",
        local_cols=("tenant_id",),
        remote_table="tenants",
        remote_cols=("tenant_id",),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("events", sa.Text(), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("rotated_at", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "url", name="uq_tenant_webhook_url"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=False,
        )

    with op.batch_alter_table("gateway_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "latency_ms",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "provider_cost",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "customer_cost",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "margin", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )
        if not has_gateway_tenant_fk:
            batch_op.create_foreign_key(
                "fk_gateway_requests_tenant_id", "tenants", ["tenant_id"], ["tenant_id"]
            )

    with op.batch_alter_table("metering_events", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )
        if not has_metering_tenant_fk:
            batch_op.create_foreign_key(
                "fk_metering_events_tenant_id", "tenants", ["tenant_id"], ["tenant_id"]
            )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.alter_column("org_id", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=False)
        if not has_organizations_tenant_fk:
            batch_op.create_foreign_key(
                "fk_organizations_tenant_id", "tenants", ["tenant_id"], ["tenant_id"]
            )

    with op.batch_alter_table("processed_webhook_events", schema=None) as batch_op:
        batch_op.alter_column("event_id", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.alter_column("task_id", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("org_id", existing_type=sa.TEXT(), nullable=False)
        if not has_tasks_org_fk:
            batch_op.create_foreign_key(
                "fk_tasks_org_id", "organizations", ["org_id"], ["org_id"]
            )
        if not has_tasks_tenant_fk:
            batch_op.create_foreign_key(
                "fk_tasks_tenant_id", "tenants", ["tenant_id"], ["tenant_id"]
            )

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("trust_scores", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False
        )
        batch_op.alter_column(
            "computed_at",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=False,
        )

    with op.batch_alter_table("waitlist", schema=None) as batch_op:
        batch_op.alter_column("email", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "signed_up_at",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )

    with op.batch_alter_table("wallet_snapshots", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "balance", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "reputation",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallet_snapshots", schema=None) as batch_op:
        batch_op.alter_column(
            "reputation",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "balance", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("waitlist", schema=None) as batch_op:
        batch_op.alter_column(
            "signed_up_at",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column("email", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("trust_scores", schema=None) as batch_op:
        batch_op.alter_column(
            "computed_at",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("org_id", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("task_id", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("processed_webhook_events", schema=None) as batch_op:
        batch_op.alter_column("event_id", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("org_id", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("metering_events", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("gateway_requests", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "margin", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "customer_cost",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "provider_cost",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "latency_ms",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column("tenant_id", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    op.drop_table("webhooks")
    # ### end Alembic commands ###
